### ISSUE TITLE
Suggestion: Ability to blacklist specific item IDs from triggering detection.

### ISSUE THREAD

**Issue by DrasMead** [someaddons/Leaky#1]
I've noticed that the 'Detected Farm Leak' message gets triggered whenever underwater structures generate amongst a bunch of kelp (as the structure forcefully breaks the kelp causing it to drop its item which then starts floating). Of course it's nice to know when this happens in some instances, but it would be just as helpful if we could somehow blacklist certain items (such as 'minecraft:kelp') from triggering the detection notification all together.

Just an idea anyway. This mod works wonders for farms and contraptions, particularly when messing around with Create. Keep up the great work! :)

**Comment by someaddons** [comment]
I think you can just increase the detection count a little and it shouldnt happen anymore :) Since world gen shouldnt not spawn that absurd amounts in total
