### ISSUE TITLE
[Compatibility]: staaaaaaaaaaaack mod

### ISSUE THREAD

**Issue by KostromDan** [someaddons/Leaky#2]
### Describe the bug you're experiencing

https://www.curseforge.com/minecraft/mc-mods/staaaaaaaaaaaack
Mod doesn't say nothing if even 1M items dropped.
![image](https://github.com/someaddons/Leaky/assets/90044015/66726b02-10b1-4a57-84b0-0a31002a6ade)

### Reproducability

-

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

-

**Comment by someaddons** [comment]
Thats totally fine, if you want to limit the stacking that stacking mod should probably have a config, leaky is only for detecting too many item entities, not stacked items (in your picture the item entities are the floating items with a number above their head, so 8 total)
