### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by Thunderrock424242** [someaddons/Leaky#3]
for 1.20.1 since i use this version could you make a command that clears all items that are not in a chest or a storage container from the world like /clear items.

**Comment by someaddons** [comment]
Vanilla already lets you kill those items, though that approach has a couple issues, like only solving the issue temporarily, accidently deleting just dropped player items etc.
With this mod you actually dont need to do it though, the mod already delete items when there is too many and reduces the lag those items cause by a lot, so its no longer an issue
